name: CI/CD

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v4
       with:
         python-version: '3.10'
         
     - uses: actions/cache@v3
       with:
         path: |
           venv
           ~/.cache/pip
         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
         restore-keys: |
           ${{ runner.os }}-pip-

     - name: Install dependencies
       run: |
         python -m venv venv
         source venv/bin/activate
         pip install -r requirements.txt
         playwright install

     - name: Run tests
       run: |
         source venv/bin/activate
         pytest tests/unit/ --cov=src --junitxml=test-results/junit.xml
         pytest tests/integration/
         pytest tests/e2e/

 security:
   needs: test
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     
     - name: Build image
       run: docker build -t app:test .
     
     - name: Check Trivy version
       run: |
         curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
         trivy --version
     
     - name: Run Trivy vulnerability scanner
       run: |
         trivy image --format table --exit-code 1 --ignore-unfixed --severity CRITICAL,HIGH app:test

 deploy:
   needs: security
   if: github.ref == 'refs/heads/main'
   runs-on: ubuntu-latest
   environment: production
   steps:
     - uses: actions/checkout@v4
     
     - uses: docker/setup-buildx-action@v3
     
     - uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
         
     - uses: docker/build-push-action@v5
       with:
         push: true
         tags: |
           greghoff/module8_is601:latest
           greghoff/module8_is601:${{ github.sha }}
         platforms: linux/amd64,linux/arm64
         cache-from: type=registry,ref=greghoff/module8_is601:cache
         cache-to: type=inline,mode=max
